# Generated by Django 4.2.6 on 2024-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilestatus',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofilestatus',
            name='status_id',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
