# Generated by Django 4.2.6 on 2024-12-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='id',
        ),
    ]
