# Generated by Django 4.2.6 on 2024-12-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_user_id_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='user_id',
        ),
    ]
